source 'https://rubygems.org'

gem 'active_record_migrations'
gem 'activerecord'
gem 'annotate', group: :development
gem 'cabocha'
gem 'sqlite3'
gem 'twitter'

group :test do
  gem 'rspec'
  gem 'reek',    require: false
  gem 'rubocop', require: false
end
